### ISSUE TITLE
Revising the overall workflow of MOHA-Kafka

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#12]
In order to remove the dependencies of Kafka libraries, we need to revise the overall workflow of MOHA-Kafka as followings by adopting the concept of KOHA(building a Kafka-based distributed queue system on the fly in a Hadoop cluster):

1) Uploads Kafka-related files (e.g. Kafka binary) into the HDFS
2) Get containers allocated for the Kafka brokers 
3) Install the Kafka library in the allocated containers and configure the Kafka
4) Launch the Kafka cluster on top of allocated containers

5) Get a container allocated for the MOHA Manager
6) MOHA Manager creates a MOHA Job Queue on top of the created Kafka cluster
7) MOHA Manager splits a MOHA Job into multiple tasks and inserts them into the MOHA Job Queue
8) MOHA Manager performs resources allocations through YARN for the MOHA TaskExecutors
9) MOHA Manager launches MOHA TaskExecutors on top of allocated containers
10) MOHA TaskExecutors start pulling tasks from the MOHA Job Queue and process them

**Comment by IDPL-MJU** [comment]
For the purpose of easy testing and implementation, for now, let's split this workflow into two major functionalities as followings:

> KOHA Part: 1) ~ 4)
> 
> MOHA Part: 5) ~ 10)

In this way, we can keep running the Kafka cluster (as we have done in our dedicated MOHA Testbed) and submit multiple MOHA applications without repeating the creation/destruction of the Kafka cluster.

One major issue is to safely connect the KOHA and MOHA parts together by passing some arguments from KOHA to MOHA. These arguments can be IP address/Port Number of Kafka cluster which can be created in any node in a cluster. Once the MOHA knows the location of the Kafka cluster, the rest of the part will not have any major problem. However, we need to thoroughly think about this !

**Comment by nguyenngoccao** [comment]
The implementation of the KOHA and MOHA workflows is almost completed. The new version of codes will be available next couple of days.
