### ISSUE TITLE
Revising the metadata management based on MySQL

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#13]
For now, we are utilizing the MySQL database to record various statistics about the MOHA execution.
However, this might be a problem in another testbed where the system administrator would not allow us to install the MySQL on any server.

Therefore, we can add a functionality that can **turn on (or off) the MySQL based metadata store** and **leave similar information in the logs** also. 

In this way, even if we cannot utilize the MySQL database, we can post-process the log files to extract information about the MOHA execution.

**Comment by nguyenngoccao** [comment]
A final static variable is added, and it allows to enable/disable the function of Mysql information log. 

final static boolean DEBUG_MYSQL = true/false;

"true" to enable the function/required pre-install Mysql server
"false" to disable the function/not required installed Mysql server
