### ISSUE TITLE
Implementing the metadata management revision

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#15]
Based on the design in issue #13, we need to implement this functionality.

**Comment by nguyenngoccao** [comment]
The implementation of this functionality is completed by adding a final static variable, and it allows to enable/disable the function of Mysql information log. 

final static boolean DEBUG_MYSQL = true/false;

"true" to enable the function/required pre-install Mysql server
"false" to disable the function/not required installed Mysql server
