### ISSUE TITLE
Deleting a Kafka Topic

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#20]
When we delete a topic in the Kafka cluster, we can use the following command.

**bin/kafka-topics.sh --delete --topic topic_name --zookeeper localhost:2181**

Then, this generates an interesting message as followings:

> Note: This will have no impact if delete.topic.enable is not set to true.

So, unless we set the **delete.topic.enable** to be **true**, the topics will remain as "marked for deletion".
Therefore, we have to set this variable in the **$KAFKA_HOME/config/server.properties** file as true to actually delete the designated topics.

**Comment by IDPL-MJU** [comment]
Cao, you can use this settings in your implementation to configure the "server.properties" file in the MOHA implementation.

**Comment by nguyenngoccao** [comment]
This setting really works.  I have updated by adding following codes

if (line.contains("#delete.topic.enable=true")) {
					line = line.replace("#delete.topic.enable=true", "delete.topic.enable=true");
					LOG.info("Enable delete topic immediately");
					debugLogger.info(line);
				}
