### ISSUE TITLE
Testing the functionality of MOHA on the Testbed

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#21]
Recently, we have added three new nodes (hdp04 ~ hdp06) to our MOHA Testbed.
These new machines basically have same YARN configurations with existing hdp01, hdp02, hdp03 nodes, however with less number of CPU cores (i.e. hdp01 ~ hdp03 have 24 cores while hdp04 ~ hdp06 have 12 cores). But, the other H/W specs including main memory and HDDs are the same.

Therefore, we need to test the functionality of our MOHA-Kafka on top of this newly configured testbed.

1) Testing the building of Kafka cluster across all 6 nodes in the testbed.

2) Testing the submission of MOHA Jobs and check if containers can be allocated and executed safely on these new nodes.

Please report any problems during the test period so that we can stabilize our newly configured testbed.

**Comment by nguyenngoccao** [comment]
I  conducted some test cases following your settings. It seemed like new servers worked well and I got the good results.
