### ISSUE TITLE
Allows to start only one broker (hdp01) for debugging queue instead of 3

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#22]
I just found that some codes are changed in the MOHA-Kafka as followings:

c378625ee053daad5ca2e42bfd27fd79d5adefa8

It looks like now, we can start only one broker (instead of launching it on every machine) in hdp01 for debugging purpose, right?.

Does this mean that we have some options to start our Kafka brokers on _any nodes_ in the system for the debugging purpose? Or from now on, we are using _only hdp01 node_ for launching the debugging purpose Kafka broker?

I think, if we want to give some flexibility for launching Kafka brokers of debugging purpose, this information also should be described in the "MOHA.conf" file. Unless, we have to hard-code the IP address of the hdp01 in the source codes which can limit the portability of our codes.

**Comment by nguyenngoccao** [comment]
I have reflected your idea through new update
