### ISSUE TITLE
Re-design of MOHA TaskExecutor

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#32]
Based on the changes in the MOHA Client and Manager described in the Issue #26, #29, the functionality of MOHA TaskExecutor should be changed as followings:

- MOHA TaskExecutor now should be able to understand the meaning of more complex _task description_ provided by the MOHA Client. It should interpret the execution structure of an MTC application, prepare a safe environment, download required data files, perform task processing and uploading the output files when all of task processing is completed.
- If the data locality is leveraged, the MOHA TaskExecutor may have to request _specific_ tasks from the MOHA Job Queue whose required data files are already residing in the current working node of the TaskExecutor.

For now, we can first implement simple job processing scheme without considering the data locality, however, we need to further investigate this functionality as the overall project makes progress.

**Comment by IDPL-MJU** [comment]
Review this re-design of MOHA TaskExecutor and update/add contents if needed.

**Comment by nguyenngoccao** [comment]
The new implementation makes MOHA TaskExecutor capable of executing Autodock-Vina tasks and potentially supports similar MTC applications. It still requires improvement to support common MTC application in generic manner.
