### ISSUE TITLE
Code Updates of the MOHA_Client Class

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#7]
I have updated some logics in the MOHA_Client class and left comments starting with "//[UPDATE]".
We can also see the overall changes in the following commit log.

5da9e02ab20daf4fc38265b1e0a31fcfc6c6f985

Please review the changes and reflect them into the local repository and let us know if there are any problems.

**Comment by nguyenngoccao** [comment]
I have checked the code and It seems to be a good update. I have compiled it without any problem.
