### ISSUE TITLE
Code Review of MOHA_Client Class

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#8]
In the "run" function (lines 231-234), following codes seem to be awkward.

int maxMemory = appResponse.getMaximumResourceCapability().getMemory();
if (managerMemory > (maxMemory / 2)) {
    managerMemory = maxMemory / 2;
}

In the YARN configuration, we already set the maximum available amount of memory for any containers in our cluster. Therefore, I think we don't need to limit the maximum memory for the MOHA_Manager as a half of the available YARN container memory (which has already a limit compared to the system memory).

**Comment by nguyenngoccao** [comment]
I was not sure that YARN whether denies the request or accepts to launch automatically for lower memory container, that why I did so. But for now, as long as your information is correct, we can remove these codes.

**Comment by IDPL-MJU** [comment]
O.K. If you think those codes can be removed, comment out them, update the repository and let me know. Then, I will close this issue.

**Comment by nguyenngoccao** [comment]
I have updated by changing limitation of memory from 50% to 100% of available memory.

**Comment by IDPL-MJU** [comment]
Based on our discussion, it will be better to have a code to check at least the required memory for the MOHA_Manager is not exceeding the available container memory by YARN.
