### ISSUE TITLE
Analysis of the Drug Repositioning Application

### ISSUE THREAD

**Issue by IDPL-MJU** [jiksoo75/MOHA-Kafka#9]
We need to analyze the behavior of Drug Repositioning application which is an example of Many-Task Computing applications.
- Executable (Autodock Vina)
- Input Parameters
- Command line options
- Output files

**Comment by nguyenngoccao** [comment]
I am working on it.

**Comment by IDPL-MJU** [comment]
[Autodock_Analysis.pdf](https://github.com/jiksoo75/MOHA-Kafka/files/502241/Autodock_Analysis.pdf)
Analysis of basic concepts and execution model of Autodock application --> Review is necessary.
